// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004211106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Jewelry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("JewelryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jewelry_type");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jewelries");

                    b.HasIndex("JewelryType")
                        .HasDatabaseName("ix_jewelries_jewelry_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jewelries_status");

                    b.ToTable("jewelries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JewelryCareSchedules.JewelryCareSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("JewelryId")
                        .HasColumnType("uuid")
                        .HasColumnName("jewelry_id");

                    b.Property<DateTime>("NextServiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_service_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jewelry_care_schedules");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_jewelry_care_schedules_is_active");

                    b.HasIndex("JewelryId")
                        .HasDatabaseName("ix_jewelry_care_schedules_jewelry_id");

                    b.HasIndex("NextServiceDate")
                        .HasDatabaseName("ix_jewelry_care_schedules_next_service_date");

                    b.ToTable("jewelry_care_schedules", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JewelryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<Guid>("JewelryId")
                        .HasColumnType("uuid")
                        .HasColumnName("jewelry_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jewelry_orders");

                    b.HasIndex("JewelryId")
                        .HasDatabaseName("ix_jewelry_orders_jewelry_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_jewelry_orders_order_number");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("ix_jewelry_orders_scheduled_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jewelry_orders_status");

                    b.ToTable("jewelry_orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
